# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff60dd222e75ec6df3f17495c139f416d6584678e9ad1d3a4069559282d845d7a0ab3fdc2aa1c416b3a7cadf0055e0648320b2e92c128e82a3981cf91b768e40

test:
  secret_key_base: 43b8b1dbcd2850e929df85b2eaa119114c9a41cfae34aff4c5a5727b76c480156015ff286e6ab730b472b4e8a3def81d9e24265c9235ca1dfbea92ee6164c8eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
